services:
  - type: web
    name: salaahshots-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
